# Generated by Django 5.0.3 on 2024-03-23 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=256, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma Tarihi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı Adı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kayıt",
                "verbose_name_plural": "    Tanım: Kayıtlar",
            },
        ),
    ]
